-- MySQL Script generated by MySQL Workbench
-- mar. 03 oct. 2017 09:51:15 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tweetbase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tweetbase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tweetbase` ;
USE `tweetbase` ;

-- -----------------------------------------------------
-- Table `tweetbase`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweetbase`.`organization` (
  `idorganization` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `website_url` VARCHAR(45) NULL,
  PRIMARY KEY (`idorganization`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tweetbase`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweetbase`.`user` (
  `iduser` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `organization_idorganization` INT NOT NULL,
  PRIMARY KEY (`iduser`, `organization_idorganization`),
  INDEX `fk_user_organization1_idx` (`organization_idorganization` ASC),
  CONSTRAINT `fk_user_organization1`
    FOREIGN KEY (`organization_idorganization`)
    REFERENCES `tweetbase`.`organization` (`idorganization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tweetbase`.`tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweetbase`.`tweet` (
  `idtweet` INT NOT NULL,
  `content` VARCHAR(45) NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idtweet`),
  INDEX `fk_tweet_user_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_tweet_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `tweetbase`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
